name: Enviar mensaje de WhatsApp

on:
  push:
    branches:
      - main # Ejecutar el workflow cuando se haga un push a la rama main

jobs:
  send-whatsapp:
    runs-on: ubuntu-latest # Usar una máquina virtual con Ubuntu
    environment: whatsapp # Especificar el environment

    steps:
      # Paso 1: Checkout del repositorio
      - name: Checkout código
        uses: actions/checkout@v3

      # Paso 2: Configurar Python
      - name: Configurar Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11" # Usar Python 3.11

      # Paso 3: Instalar dependencias
      - name: Instalar dependencias
        run: |
          python -m pip install --upgrade pip
          pip install twilio python-dotenv

      # Paso 4: Mostrar variables de entorno (depuración)
      - name: Mostrar variables de entorno
        env:
          TWILIO_ACCOUNT_SID: ${{ secrets.TWILIO_ACCOUNT_SID }}
          TWILIO_AUTH_TOKEN: ${{ secrets.TWILIO_AUTH_TOKEN }}
          GITHUB_ACTOR: ${{ github.actor }}
          GITHUB_REPOSITORY: ${{ github.repository }}
          GITHUB_REF: ${{ github.ref }}
        run: |
          echo "TWILIO_ACCOUNT_SID: $TWILIO_ACCOUNT_SID"
          echo "TWILIO_AUTH_TOKEN: $TWILIO_AUTH_TOKEN"
          echo "GITHUB_ACTOR: $GITHUB_ACTOR"
          echo "GITHUB_REPOSITORY: $GITHUB_REPOSITORY"
          echo "GITHUB_REF: $GITHUB_REF"

      # Paso 5: Ejecutar el script
      - name: Enviar mensaje de WhatsApp
        env:
          TWILIO_ACCOUNT_SID: ${{ secrets.TWILIO_ACCOUNT_SID }}
          TWILIO_AUTH_TOKEN: ${{ secrets.TWILIO_AUTH_TOKEN }}
          GITHUB_ACTOR: ${{ github.actor }}
          GITHUB_REPOSITORY: ${{ github.repository }}
          GITHUB_REF: ${{ github.ref }}
        run: |
          python scripts/send_whatsapp.py
