name: Enviar mensaje de WhatsApp

on:
  push:
    branches:
      - main # Ejecutar el workflow cuando se haga un push a la rama main

jobs:
  send-whatsapp:
    runs-on: ubuntu-latest
    environment: whatsapp # Especificar el environment

    steps:
      # Paso 1: Checkout del repositorio
      - name: Checkout código
        uses: actions/checkout@v3

      # Paso 2: Configurar Python
      - name: Configurar Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11" # Usar Python 3.11

      # Paso 3: Instalar dependencias
      - name: Instalar dependencias
        run: |
          python -m pip install --upgrade pip
          pip install twilio python-dotenv

      # Paso 4: Mostrar el mensaje del commit
      - name: Mostrar mensaje del commit
        run: |
          echo "Mensaje del commit: ${{ github.event.head_commit.message }}"

      # Paso 5: Ejecutar el script
      - name: Enviar mensaje de WhatsApp
        env:
          TWILIO_ACCOUNT_SID: ${{ secrets.TWILIO_ACCOUNT_SID }}
          TWILIO_AUTH_TOKEN: ${{ secrets.TWILIO_AUTH_TOKEN }}
          GITHUB_ACTOR: ${{ github.actor }}
          GITHUB_REPOSITORY: ${{ github.repository }}
          GITHUB_REF: ${{ github.ref }}
          GITHUB_COMMIT_MESSAGE: ${{ github.event.head_commit.message }} # Mensaje del commit
        run: |
          python scripts/send_whatsapp.py
